dashboard/blueprint.py
from flask import Blueprint, render_template, current_app

import pandas as pd
import json
import plotly
import plotly.express as px


dashboard_blueprint = Blueprint('dashboard', __name__,
    template_folder='templates',
    static_folder='static', static_url_path='assets')

@dashboard_blueprint.route('/')
def db_blueprint_dashboard():

    print(current_app.config['loggedin'])

    if current_app.config['loggedin'] == 'false':
        return render_template('login.html')

    else:

        sample_data = pd.DataFrame({
                "Vegetables": ["Lettuce", "Cauliflower", "Carrots", "Lettuce", "Cauliflower", "Carrots"],
                "Amount": [10, 15, 8, 5, 14, 25],
                "City": ["London", "London", "London", "Madrid", "Madrid", "Madrid"]
            })

        fig = px.bar(sample_data, x="Vegetables", y="Amount", color="City", barmode="stack")
        fig2 = px.bar(sample_data, x="City", y="Amount", color="Vegetables", barmode="group")
        
        print('fig: ', fig)
        graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder) #transform to json
        graphJSON2 = json.dumps(fig2, cls=plotly.utils.PlotlyJSONEncoder)
        print('graphJSON: ', graphJSON)

        return render_template('dashboard.html', graphJSON=graphJSON, graphJSON2=graphJSON2)

templates/about.html
{% extends 'base.html' %}

{% block title%}About page{% endblock %}

{% block content %}

<h1>About page</h1>

<p>
    This is about page
</p>

{% endblock %}

templates/account.html
{% extends 'base.html' %}
{% include 'header.html' %}
{% block title %} Home {% endblock %}
{% block body %}

<div>
    <div class="container">
        <div class="row justify-content-center algin-items-center">
            <br />
            <p>Your account details are below: 
            </p>
            <table class="table table-striped">
                <tr>
                    <td>Username:</td>
                    <td>{{ account.username }}
                    </td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td>{{ account.email }} </td>
                </tr>
                <tr>
                    <td>Account type:</td>
                    <td>{{ account.account_type }}</td>
                </tr>
                <tr>
                    <td>Account ID:</td>
                    <td>{{ account.id }}</td>
                </tr>
                <tr>
                    <td>Account MRN:</td>
                    <td>{{ account.mrn }}</td>
                </tr>
                

                <!-- MODAL WINDOW FOR EDITING -->
            
                <div id="modaledit{{ account.id }}" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Update Information</h4>
                            </div>
                            <div class="modal-body">
                                <form action="{{url_for('update_account')}}" method="POST">

                                <div class="form-group">
                                        <label for="username">Username</label>
                                        <input type="text" class="form-control" name="username" value="{{account.username}}" >
                                </div>    

                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="text" class="form-control" name="email" value="{{account.email}}">
                                </div>


                                <div class="form-group">
                                    <label for="account_type">Account Type</label>
                                    <input type="text" class="form-control" name="account_type" value="{{account.account_type}}" readonly >
                            </div>    

                                <div class="form-group">
                                    <label for="id">ID</label>
                                    <input type="text" class="form-control" name="id" value="{{account.id}}" readonly>
                            </div>    


                            <div class="form-group">
                                <label for="mrn">MRN</label>
                                <input type="text" class="form-control" name="mrn" value="{{account.mrn}}" readonly >
                        </div>    


                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Update</button>
                                </div>

                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

             
            </table>
            <a href="/update_account/{{account.id}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{account.id}}">Edit</a>    
        </div>
    </div>            
            
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>
            {% block title %} 
            {% endblock %} 
    </title>
</head>
<body>

{% block body %} 

{% endblock %}


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/careteam.html
<!DOCTYPE html>
<html lang="en">
  <head>        
      <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css') }}"> 
  </head>

  <body>
    <main>
        <div class="container">
          <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
              <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>
      
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
              <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
              <li><a href="/about" class="nav-link px-2 link-dark">About</a></li>
              <li><a href="/careteam" class="nav-link px-2 link-dark">Care Team</a></li>
              <li><a href="/contact" class="nav-link px-2 link-dark">Contact Us</a></li>

            </ul>
      
            <div class="col-md-3 text-end">
              <a href="/login" class="btn btn-outline-primary me-2">Login</a>
              <a href="/register" class="btn btn-primary">Register</a>
            </div>
          </header>
        </div>

    <header class="text-center">
        <h2> Meet Our Care Team</h2>
    </header>

    <link rel="stylesheet" href="{{ url_for('static', filename='careteam.css') }}"> 
   
    <section class="text-center">
      <div class="row">
        <div class="gallery">
          <a target="_blank" href="careteam">
            <img src="https://raw.githubusercontent.com/rimashah1/PssP-enhancements/main/images/doctor1.jpg" alt="Primary Care Physician" width="300" height="300">
          </a>
          <div class="desc">Dr. Mia</div>
          <p> Dr. Mia has been a physician for 7 years. She earned her MD from Stony Brook School of Medicine and completed her residency at NYU Langone. In her spare time, she enjoys concerts and rock climbing. </p>
        </div>

        <div class="gallery"> 
            <a target="_blank" href="careteam">
              <img src="https://raw.githubusercontent.com/rimashah1/PssP-enhancements/main/images/doctor2.jpg" alt="Primary Care Physician" width="300" height="300">
            </a>
            <div class="desc">Dr. Alex</div>
            <p> Dr. Alex has been a physician for 10 years. He earned his MD from Stony Brook School of Medicine and completed his residency at NYU Langone. In his spare time, he enjoys building Lego sets and crocheting. </p>
        </div>

        <div class="gallery">
          <a target="_blank" href="careteam">
            <img src="https://raw.githubusercontent.com/rimashah1/PssP-enhancements/main/images/nurse1.jpg" alt="Nurse" width="300" height="300">
          </a>
          <div class="desc">Nurse Nora</div>
          <p> Dr. Mia has been a nurse for 6 years. She earned her degree from Stony Brook School of Nursing. In her spare time, she enjoys col. </p>
        </div>
    
        <div class="gallery">
          <a target="_blank" href="careteam">
            <img src="https://raw.githubusercontent.com/rimashah1/PssP-enhancements/main/images/nurse2.jpg" alt="Nurse" width="300" height="300">
          </a>
          <div class="desc">Nurse Laila</div>
          <p> Dr. Mia has been a physician for 10 years. She earned her degree from Stony Brook School of Nursing. In her spare time, she enjoys video games and pilates. </p>
        </div>
      </div>
    </section>

    <footer>
        <br />
        <a href="/" class="btn btn-primary">Home</a>
    </footer>  

  </body>

</html>

templates/header.html
{% extends 'base.html' %}

{% block title %} 
    Patient Portal
{% endblock %}



{% block body %}

    <!-- insert bootstrap nav bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Patient Portal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="/">Home</a>
                    <a class="nav-link" href="{{ url_for('dashboard.db_blueprint_dashboard') }}">Dashboard</a>
                    <a class="nav-link" href="{{ url_for('get_gui_patients') }}">Patient</a>
                    <a class="nav-link" href="">Messaging</a>
                    <a class="nav-link" href="">Settings</a>
                    <a class="nav-link" href="{{ url_for('account') }}">Account</a>
                </div>
            </div>

            <div class="col-md-3 text-end">
                <a href="{{ url_for('logout') }}" class="btn btn-primary float-right">Logout</a>
            </div>

        </div>
    </nav>


    <br />


    <!-- <div class="jumbotron p-3">
        <div class="well text-center">
            <h1>Patient Self Service Portal (PssP - Admin v.02) </h1>
        </div>
    </div> -->

{% endblock %}

templates/landing.html
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Patient Portal</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/starter-template/">
  
    
      <!-- Bootstrap core CSS -->
  <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  
      <!-- Favicons -->
  <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
  <meta name="theme-color" content="#7952b3">
  
  
      <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
      </style>
  
      
      <!-- Custom styles for this template -->
      <link href="heroes.css" rel="stylesheet">
    </head>
   
    <body>
    
      <main>
        <div class="container">
          <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
              <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>
      
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
              <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
              <li><a href="/about" class="nav-link px-2 link-dark">About</a></li>
              <li><a href="/careteam" class="nav-link px-2 link-dark">Care Team</a></li>
              <li><a href="/contact" class="nav-link px-2 link-dark">Contact Us</a></li>

            </ul>
      
            <div class="col-md-3 text-end">
              <a href="/login" class="btn btn-outline-primary me-2">Login</a>
              <a href="/register" class="btn btn-primary">Register</a>
            </div>
          </header>
        </div>


        <div class="px-4 py-5 my-5 text-center">
          <img class="d-block mx-auto mb-4" src="https://raw.githubusercontent.com/rimashah1/PssP-enhancements/main/images/rima-health-logo.jpg" alt="" width="100" height="100">
          <h1 class="display-5 fw-bold">Rima Health Patient Portal </h1>
          <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Designed to make managing your medical care and records easier.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
              <button type="button" class="btn btn-primary btn-lg px-4 gap-3">About Us</button>
            </div>
          </div>
        </div>
      
        <div class="b-example-divider"></div>
      
        <div class="px-4 pt-5 my-5 text-center border-bottom">
          <h1 class="display-4 fw-bold">Create Your Patient Portal Account Today </h1>
          <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Have 24/7 access to your personal medical records and make informed decisions about your health.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
              <button type="button" class="btn btn-primary btn-lg px-4 me-sm-3">Learn More</button>
            </div>
          </div>
          <div class="overflow-hidden" style="max-height: 30vh;">
            <div class="container px-5">
              <img src="https://getbootstrap.com/docs/5.0/examples/heroes/bootstrap-docs.png" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Image of dashboard" width="700" height="500" loading="lazy">
            </div>
          </div>
        </div>
      
        <div class="b-example-divider"></div>
      
        <div class="container col-xxl-8 px-4 py-5">
          <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
            <div class="col-10 col-sm-8 col-lg-6">
              <img src="https://getbootstrap.com/docs/5.0/examples/heroes/bootstrap-themes.png" class="d-block mx-lg-auto img-fluid" alt="Image of Care Team page" width="700" height="500" loading="lazy">
            </div>
            <div class="col-lg-6">
              <h1 class="display-5 fw-bold lh-1 mb-3">Communicate with your Care Providers</h1>
              <p class="lead">Send and recieve secure messages with your doctor. </p>
              <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                <a href="/careteam" class="btn btn-primary btn-lg px-4 me-md-2">Meet Our Care Team</a>
              </div>
            </div>
          </div>
        </div>
  
    
      </main>
      
      
          <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      
            
        
      
      </body>
</html>
 
    


<!-- THIS IS THE PART BELOW THAT CAME WITH IT, WE NEED TO UPDATE THE LOCATION -->
<!-- <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> -->
<!-- THIS HERE NOW IS THE CORRECT LOCATION BELOW.... -->
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css') }}"> 


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    

templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Signin Template · Bootstrap v5.2</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css') }}"> 
<!-- <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <!-- <link href="signin.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='signin.css') }}"> 

  </head>
  <body class="text-center">
    
    <main class="form-signin w-100 m-auto">

      <form action="{{ url_for('login') }}" method="post">
        <h1 class="h3 mb-3 fw-normal">Login</h1>

        <div class="form-floating" style="padding: .2em">
          <input type="text" class="form-control" id="username" name="username">
          <label for="floatingInput">Username</label>
        </div>

        <div class="form-floating" style="padding: .2em">
          <input type="password" class="form-control" id="password" name="password">
          <label for="floatingPassword">Password</label>
        </div>

        <div class="msg">{{ msg }}</div>

        <br />
        
        <div class="form-group">
          <button class="btn btn-primary" type="submit" value="Login">Login</button>
          <br>
          <br>
          <a href="{{ url_for('register') }}" class="btn btn-primary">Register</a>

        </div>


      </form>


    </main>
  </body>
</html>

templates/patient_all.html
{% extends 'base.html' %}
{% include 'header.html' %}
{% block title %} Home {% endblock %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">



                <h2 style="margin-bottom: 1em;"> Manage Patients 
                    <button type="button" class="btn btn-success float-right"
                        data-toggle="modal" data-target="#mymodal">Add New Patient
                    </button> 
                </h2>


                {% with messages = get_flashed_messages() %}
                {% if messages %}
                {% for message in messages %}

                <div class="alert alert-success alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">x</span>
                    </button>

                {{message}}

                </div>


                {% endfor %}
                {% endif %}
                {% endwith %}


                <table class="table table-hover table-dark table-striped">

                    <tr>

                        <th>ID</th>
                        <th>MRN</th>
                        <th>Date of Birth</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Gender</th>
                        <th>Mobile Phone Number</th>
                        <th>Action</th>
                        
                    </tr>


                   {% for row in patients %} <!-- loop that references the table from the query all-->
                    <tr>
                        <td>{{row.id}}</td>
                        <td>{{row.mrn}}</td>
                        <td>{{row.dob}}</td>
                        <td>{{row.first_name}}</td>
                        <td>{{row.last_name}}</td>
                        <td>{{row.gender}}</td>
                        <td>{{row.contact_mobile}}</td>

                        <td>
                            <a href="/view/{{row.mrn}}" class="btn btn-info btn-xs">View</a>
                            <a href="/update/{{row.mrn}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.mrn}}">Edit</a>
                            <a href="/delete/{{row.mrn}}" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete?')">Delete</a>

                        </td>

                    </tr>


                  <!-- Modal Edit Employee-->


                  
                    <div id="modaledit{{row.mrn}}" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Update Information</h4>
                            </div>
                            <div class="modal-body">
                                <form action="{{url_for('update')}}" method="POST">
                                <div class="form-group">
                                    <label for="mrn">MRN</label>
                                    <input type="text" class="form-control" name="mrn" value="{{row.mrn}}" readonly>
                                </div>
                                <div class="form-group">
                                    <label>Date of Birth (MM-DD-YYYY)</label>
                                    <input type="text" class="form-control" name="dob" value="{{row.dob}}">
                                </div>
                                <div class="form-group">
                                    <label>First name:</label>
                                    <input type="text" class="form-control" name="first_name" value="{{row.first_name}}">
                                </div>
                                <div class="form-group">
                                    <label>Last name:</label>
                                    <input type="text" class="form-control" name="last_name" value="{{row.last_name}}">
                                </div>
                                <div class="form-group">
                                    <label>Gender:</label>
                                    <input type="text" class="form-control" name="gender" value="{{row.gender}}">
                                </div>
                                <div class="form-group">
                                    <label>Mobile Contact Number</label>
                                    <input type="text" class="form-control" name="contact_mobile" value="{{row.contact_mobile}}">
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Update</button>
                                </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                    </div>


                    {% endfor %}


                </table>


            </div>



                  <!-- Modal Add Patient-->


        <div id="mymodal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Add Patient</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{{url_for('insert')}}" method="POST">
                        <div class="form-group">
                            <label>MRN:</label>
                            <input type="text" class="form-control" name="mrn" required="1">
                        </div>
                        <div class="form-group">
                            <label>Date of Birth (MM-DD-YYYY):</label>
                            <input type="text" class="form-control" name="dob" required="1">
                        </div>
                        <div class="form-group">
                            <label>First Name:</label>
                            <input type="text" class="form-control" name="first_name" required="1">
                        </div>
                            <div class="form-group">
                            <label>Last Name:</label>
                            <input type="text" class="form-control" name="last_name" required="1">
                        </div>
                        <div class="form-group">
                            <label>Gender:</label>
                            <input type="text" class="form-control" name="gender" required="1">
                        </div>
                        <div class="form-group">
                            <label>Mobile Contact Number:</label>
                            <input type="text" class="form-control" name="contact_mobile" required="1">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Add Patient</button>
                        </div>
                        </form>

                    </div>


                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>





        </div>
    </div>
</div>


{% endblock %}